export const store = {
  name: "cell.xchange",
  phoneDisplay: "97 18 18 27 27",
  phoneE164: "+919718182727",
  email: "cell.xchange@icloud.com",
  hours: "12 p.m. – 10 p.m.",
  days: "Open all 7 days",
  addressLine1: "140/9, Kishan Garh, Vasant Kunj",
  addressLine2: "Opposite CNG Station, Near Gate No. 3, Gaushala Road",
  mapUrl: "https://www.google.com/maps/search/?api=1&query=140%2F9%20Kishan%20Garh%20Vasant%20Kunj%20Gaushala%20Road",
  brandLogo: { url: "", publicId: "" },
  heroImage: { url: "/hero-black", publicId: "" },
  heroImages: [{ url: "/hero-black", publicId: "" }],
  heroImageAlt: "Black iPhone available from cell.xchange",
  heroBannerText: "Phones · Accessories · Exchange",
  heroEyebrow: "Independent mobile store · Vasant Kunj",
  heroTitle: "A better phone.",
  heroTitleAccent: "A simpler choice.",
  heroDescription: "Verified devices, honest condition details and a local team you can message before you visit.",
  heroPrimaryCta: "See today’s devices",
  heroSecondaryCta: "Tell us what you need",
  offerBarEnabled: true,
  offerBarText: "Diwali offers now live · Special exchange bonuses · Fresh devices added regularly · Ask us for today’s best price",
  latestEyebrow: "In store now",
  latestTitle: "Start with what’s here.",
  stockEyebrow: "Your direct line to the store",
  stockTitle: "New stock moves fast.",
  stockTitleAccent: "Stay close.",
  stockDescription: "Save cell.xchange on WhatsApp. Ask for fresh arrivals, prices or a specific model whenever you’re ready—no forms and no sales queue.",
  stockCta: "Check latest stock",
  trustTitle1: "Checked before listing",
  trustText1: "Clear condition and specifications before you decide.",
  trustTitle2: "Straightforward exchange",
  trustText2: "Bring your current phone for an in-store assessment.",
  trustTitle3: "A shop you can return to",
  trustText3: "Real local support before and after your purchase.",
  visitEyebrow: "Visit cell.xchange",
  visitTitle: "See the phone.",
  visitTitleAccent: "Make the right call.",
  visitDescription: "Open every day. Walk in, call ahead or message us to confirm availability.",
  directionsCta: "Get directions",
  aboutEyebrow: "Our store",
  aboutTitle: "Local expertise.",
  aboutTitleAccent: "Straight answers.",
  aboutIntro: "cell.xchange is an independent smartphone store in Vasant Kunj, built around transparent information, carefully selected stock and service that continues after the sale.",
  beliefEyebrow: "What we believe",
  beliefTitle: "Buying a phone should feel clear.",
  beliefDescription: "No confusing bundles or vague condition grades. We explain the details that matter—performance, storage, battery, condition and price—so you can make the right choice without pressure.",
  beliefItem1: "Focused selection",
  beliefItem2: "Checked devices",
  beliefItem3: "Personal advice",
  beliefItem4: "Local support",
  contactEyebrow: "Contact & directions",
  contactTitle: "Visit cell.xchange.",
  contactDescription: "Walk in any day, call before you visit, or send us a WhatsApp message for current stock.",
  availabilityEyebrow: "Need today’s availability?",
  availabilityTitle: "Message the shop directly.",
  availabilityCta: "Chat on WhatsApp",
  footerDescription: "A trusted local destination for smartphones, exchanges and straightforward buying advice in Vasant Kunj.",
  invoiceHeader: "Proof of Purchase",
  showInvoiceHeader: true,
  invoiceTermsText: "7 days warranty on used phones.\nNo warranty on display.\nOur responsibility ceases once the goods leave our premises.\nSubject to Delhi jurisdiction.\nAfter-sales service will be provided by the respective service centre directly.",
  instagramUrl: "",
  youtubeUrl: "",
  footerWhatsappUrl: "https://wa.me/919718182727",
  showInstagram: true,
  showYoutube: true,
  showWhatsapp: true,
  whatsappUrl: "https://wa.me/919718182727?text=Hi%20cell.xchange%2C%20I%27m%20interested%20in%20a%20phone.",
};

export const editableStoreFields = Object.keys(store).filter((key) => ![
  "phoneE164",
  "whatsappUrl",
  "brandLogo",
  "heroImage",
  "heroImages",
  "offerBarEnabled",
  "showInstagram",
  "showYoutube",
  "showWhatsapp",
  "showInvoiceHeader",
].includes(key));

export function createStoreProfile(values = {}) {
  const legacyHero = values.heroImage?.url ? values.heroImage : store.heroImage;
  const heroImages = Array.isArray(values.heroImages)
    ? values.heroImages.filter((image) => image?.url).slice(0, 8)
    : [];
  if (!heroImages.length) heroImages.push(legacyHero);
  const profile = {
    ...store,
    ...values,
    brandLogo: values.brandLogo?.url ? values.brandLogo : store.brandLogo,
    heroImage: heroImages[0],
    heroImages,
  };
  const digits = String(profile.phoneDisplay || "").replace(/\D/g, "");
  profile.phoneE164 = digits.length === 10 ? `+91${digits}` : `+${digits}`;
  profile.whatsappUrl = `https://wa.me/${profile.phoneE164.replace("+", "")}?text=Hi%20${encodeURIComponent(profile.name)}%2C%20I%27m%20interested%20in%20a%20phone.`;
  return profile;
}
