import Link from "next/link";
import { ArrowRight, BadgeCheck, BatteryCharging, RefreshCw, ShieldCheck, Sparkles } from "lucide-react";
import PhoneCard from "@/components/phones/PhoneCard";
import PhoneVisual from "@/components/ui/PhoneVisual";
import { brands } from "@/lib/demo-data";
import { getPhones } from "@/services/phoneService";

export const dynamic = "force-dynamic";

export default async function HomePage() {
  const phones = await getPhones({}, 4);
  return <>
    <section className="overflow-hidden bg-[#f4f6f2]"><div className="container-shell grid min-h-[650px] items-center gap-10 py-16 lg:grid-cols-[1.15fr_.85fr] lg:py-20">
      <div className="relative z-10"><div className="mb-6 inline-flex items-center gap-2 rounded-full bg-white px-3.5 py-2 text-[11px] font-bold shadow-sm"><Sparkles size={13} className="text-[#557c35]"/> Fresh drops, every week</div><h1 className="display max-w-3xl text-[56px] font-black leading-[.93] sm:text-[76px] lg:text-[92px]">Find your<br/><span className="text-[#54715e]">perfect</span> smartphone.</h1><p className="mt-7 max-w-lg text-[16px] leading-7 text-[#626c65]">A carefully curated collection of new and pre-loved phones, with honest specs and people who actually listen.</p><div className="mt-9 flex flex-wrap gap-3"><Link href="/phones" className="inline-flex items-center gap-2 rounded-full bg-[#173f2c] px-6 py-3.5 text-sm font-bold text-white hover:gap-3">Browse phones <ArrowRight size={16}/></Link><Link href="/about#contact" className="rounded-full border border-[#cfd5cf] bg-white px-6 py-3.5 text-sm font-bold">Talk to us</Link></div></div>
      <div className="relative"><div className="absolute left-1/2 top-1/2 h-[380px] w-[380px] -translate-x-1/2 -translate-y-1/2 rounded-full bg-[#d9f99d] blur-[1px] sm:h-[480px] sm:w-[480px]"/><PhoneVisual/><div className="absolute bottom-2 left-0 rounded-2xl bg-white/90 p-4 shadow-xl backdrop-blur sm:left-8"><p className="eyebrow text-[#718078]">In stock now</p><p className="mt-1 text-sm font-black">48 handpicked devices</p></div></div>
    </div></section>
    <section className="border-y border-[#e9ebe8] py-7"><div className="container-shell flex items-center gap-7 overflow-x-auto no-scrollbar"><span className="eyebrow shrink-0 text-[#929994]">Popular brands</span>{brands.map(brand=><span key={brand} className="shrink-0 text-[15px] font-extrabold tracking-[-.03em] text-[#394139]">{brand}</span>)}</div></section>
    <section className="container-shell py-24"><div className="mb-10 flex items-end justify-between"><div><p className="eyebrow text-[#718078]">The shortlist</p><h2 className="display mt-3 text-4xl font-black sm:text-5xl">Phones worth knowing.</h2></div><Link href="/phones" className="hidden items-center gap-2 text-sm font-bold sm:flex">See all phones <ArrowRight size={15}/></Link></div><div className="grid gap-5 sm:grid-cols-2 lg:grid-cols-4">{phones.slice(0,4).map(phone=><PhoneCard key={phone._id} phone={phone}/>)}</div></section>
    <section className="bg-[#102c20] py-24 text-white"><div className="container-shell"><div className="grid gap-12 lg:grid-cols-[.75fr_1.25fr]"><div><p className="eyebrow text-[#b7d5c3]">Why Mobile Hub</p><h2 className="display mt-4 text-5xl font-black leading-[.98]">Good phones.<br/>No guesswork.</h2><p className="mt-6 max-w-sm text-sm leading-6 text-white/60">We make the complicated parts simple, so you can choose with confidence and get on with your day.</p></div><div className="grid gap-px overflow-hidden rounded-[24px] bg-white/15 sm:grid-cols-2">{[[BadgeCheck,"Quality checked","Every device passes a rigorous inspection."],[ShieldCheck,"Clear warranty","Straightforward cover, explained in plain English."],[RefreshCw,"Easy exchange","Get fair value for your current phone."],[BatteryCharging,"Battery health","Real battery condition, never hidden."]].map(([Icon,title,text])=><div key={title} className="bg-[#163928] p-7"><Icon size={24} className="text-[#d9f99d]"/><h3 className="mt-8 text-lg font-bold">{title}</h3><p className="mt-2 text-sm leading-6 text-white/55">{text}</p></div>)}</div></div></div></section>
    <section className="container-shell py-24"><div className="relative overflow-hidden rounded-[30px] bg-[#d9f99d] px-7 py-16 text-center sm:px-16"><div className="dot-grid absolute inset-0 opacity-50"/><div className="relative"><p className="eyebrow">The right phone is here</p><h2 className="display mx-auto mt-3 max-w-2xl text-4xl font-black sm:text-6xl">Ready for an upgrade?</h2><p className="mx-auto mt-5 max-w-md text-sm leading-6 text-[#455047]">Explore the latest stock or visit us for advice without the sales pitch.</p><Link href="/phones" className="mt-8 inline-flex items-center gap-2 rounded-full bg-[#173f2c] px-6 py-3.5 text-sm font-bold text-white">Find your phone <ArrowRight size={16}/></Link></div></div></section>
  </>;
}
