import { ArrowUpRight, Clock3, HeartHandshake, Mail, MapPin, Phone, ShieldCheck, Smartphone } from "lucide-react";
import { getStoreProfile } from "@/services/settingsService";

export const metadata = { title: "Our store", description: "Visit cell.xchange in Kishan Garh, Vasant Kunj. Open all seven days from 12 p.m. to 10 p.m." };

export default async function AboutPage() {
  const store = await getStoreProfile();
  return <>
    <section className="border-b border-[#e1e2df] bg-[#f5f5f2]"><div className="container-shell grid gap-12 py-20 lg:grid-cols-[.9fr_1.1fr] lg:py-28"><div><p className="eyebrow flex items-center gap-3 text-[#777a80]"><span className="h-px w-8 bg-black"/>Our store</p><h1 className="display mt-7 text-5xl font-semibold leading-[.98] sm:text-7xl">Local expertise.<br/><span className="text-[#70737a]">Straight answers.</span></h1></div><div className="flex items-end"><p className="max-w-xl text-lg leading-8 text-[#5f6268]">cell.xchange is an independent smartphone store in Vasant Kunj, built around transparent information, carefully selected stock and service that continues after the sale.</p></div></div></section>
    <section className="container-shell py-24"><div className="grid border border-[#dedfdd] lg:grid-cols-[1.05fr_.95fr]"><div className="bg-[#0b0c0e] p-9 text-white sm:p-14"><p className="eyebrow text-white/40">What we believe</p><h2 className="display mt-5 max-w-lg text-4xl font-semibold leading-[1.02] sm:text-6xl">Buying a phone should feel clear.</h2><p className="mt-7 max-w-md text-sm leading-7 text-white/50">No confusing bundles or vague condition grades. We explain the details that matter—performance, storage, battery, condition and price—so you can make the right choice without pressure.</p></div><div className="technical-grid grid grid-cols-2 gap-px bg-[#dedfdd] p-px">{[[Smartphone,"Focused selection"],[ShieldCheck,"Checked devices"],[HeartHandshake,"Personal advice"],[MapPin,"Local support"]].map(([Icon,text]) => <div key={text} className="flex min-h-40 flex-col justify-between bg-white p-6 sm:min-h-48 sm:p-8"><Icon size={22}/><span className="text-sm font-semibold">{text}</span></div>)}</div></div></section>
    <section id="contact" className="border-y border-[#dedfdd] bg-[#f5f5f2]"><div className="container-shell grid lg:grid-cols-[.7fr_1.3fr]"><div className="border-b border-[#dedfdd] py-14 lg:border-b-0 lg:border-r lg:pr-12"><p className="eyebrow text-[#777a80]">Contact & directions</p><h2 className="display mt-5 text-4xl font-semibold sm:text-5xl">Visit cell.xchange.</h2><p className="mt-5 max-w-sm text-sm leading-7 text-[#686b71]">Walk in any day, call before you visit, or send us a WhatsApp message for current stock.</p></div><div className="grid sm:grid-cols-2"><a href={store.mapUrl} target="_blank" rel="noreferrer" className="border-b border-[#dedfdd] p-7 hover:bg-white sm:border-r lg:p-10"><MapPin size={21}/><p className="eyebrow mt-8 text-[#85888d]">Shop address</p><p className="mt-3 text-sm font-semibold leading-6">{store.addressLine1}<br/><span className="font-normal text-[#696c72]">{store.addressLine2}</span></p><span className="mt-5 inline-flex items-center gap-1 text-xs font-bold">Open in Maps <ArrowUpRight size={13}/></span></a><div className="border-b border-[#dedfdd] p-7 lg:p-10"><Clock3 size={21}/><p className="eyebrow mt-8 text-[#85888d]">Opening hours</p><p className="mt-3 text-sm font-semibold leading-6">{store.hours}<br/><span className="font-normal text-[#696c72]">{store.days}</span></p></div><a href={`tel:${store.phoneE164}`} className="border-b border-[#dedfdd] p-7 hover:bg-white sm:border-b-0 sm:border-r lg:p-10"><Phone size={21}/><p className="eyebrow mt-8 text-[#85888d]">Phone</p><p className="mt-3 text-sm font-semibold">{store.phoneDisplay}</p></a><a href={`mailto:${store.email}`} className="p-7 hover:bg-white lg:p-10"><Mail size={21}/><p className="eyebrow mt-8 text-[#85888d]">Email</p><p className="mt-3 break-all text-sm font-semibold">{store.email}</p></a></div></div></section>
    <section className="container-shell py-24"><div className="flex flex-col items-start justify-between gap-8 border-b border-black pb-12 sm:flex-row sm:items-end"><div><p className="eyebrow text-[#777a80]">Need today’s availability?</p><h2 className="display mt-4 text-4xl font-semibold sm:text-5xl">Message the shop directly.</h2></div><a href={store.whatsappUrl} target="_blank" rel="noreferrer" className="bg-[#1f55ff] px-6 py-4 text-xs font-bold uppercase tracking-[.12em] text-white">Chat on WhatsApp</a></div></section>
  </>;
}
